import { createContext, useContext, useState, useEffect } from 'react'
import type { ReactNode } from 'react'

export type Language = 'hi' | 'ta' | 'te' | 'kn' | 'ml' | 'gu' | 'mr' | 'bn' | 'pa' | 'ur' | 'en' | 'ne' | 'si' | 'th' | 'my-MM' | 'km' | 'id' | 'my' | 'es' | 'fr' | 'fil'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider')
  }
  return context
}

interface LanguageProviderProps {
  children: ReactNode
}

export const LanguageProvider = ({ children }: LanguageProviderProps) => {
  const [language, setLanguageState] = useState<Language>(() => {
    try {
      if (typeof window !== 'undefined' && window.localStorage) {
        const saved = localStorage.getItem('language') as Language
        if (saved && ['hi', 'ta', 'te', 'kn', 'ml', 'gu', 'mr', 'bn', 'pa', 'ur', 'en', 'ne', 'si', 'th', 'my-MM', 'km', 'id', 'my', 'es', 'fr', 'fil'].includes(saved)) {
          return saved
        }
      }
    } catch (error) {
      console.error('Error reading language from localStorage:', error)
    }
    return 'en'
  })

  useEffect(() => {
    try {
      if (typeof window !== 'undefined' && window.localStorage) {
        localStorage.setItem('language', language)
      }
    } catch (error) {
      console.error('Error saving language to localStorage:', error)
    }
  }, [language])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
  }

  const t = (key: string): string => {
    const translations = getTranslations(language)
    return translations[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

// Extract English translations as base
const englishTranslations: Record<string, string> = {
    // Common
    'home': 'Home',
    'clients': 'Clients',
    'customer360': 'Customer 360',
    'tourPlans': 'Tour Planning',
    'eDetailing': 'E-Detailing',
    'leaves': 'Leaves',
    'samples': 'Sample Management',
    'profile': 'Profile',
    'reports': 'Reports',
    'sync': 'Sync',
    'todaysPlan': "Today's Plan",
    'dcr': 'DCR',
    'doctor360': 'Doctor Details',
    'expenseClaim': 'Expense Claim',
    'createExpenseClaim': 'Create Expense Claim',
    'orderBooking': 'Order Booking',
    'logout': 'Logout',
    'login': 'Login',
    'email': 'Email',
    'password': 'Password',
    'rememberMe': 'Remember me',
    'forgotPassword': 'Forgot Password?',
    'back': 'Back',
    'submit': 'Submit',
    'cancel': 'Cancel',
    'save': 'Save',
    'edit': 'Edit',
    'delete': 'Delete',
    'view': 'View',
    'search': 'Search',
    'filter': 'Filter',
    'all': 'All',
    'doctors': 'Doctors',
    'mrList': 'MR List',
    'tourPlanRequests': 'Tour Plan Requests',
    'managerInsights': 'Manager Insights',
    'drugSafety': 'Drug Safety',
    'visitCoverage': 'Visit Coverage',
    'salesDashboard': 'Sales Dashboard',
    'pharmacy': 'Pharmacy',
    'distributors': 'Distributors',
    'hospitals': 'Hospitals',
    'clinics': 'Clinics',
    'viewDetails': 'View Details',
    'noClientsFound': 'No clients found for this category.',
    'todaysPlanTitle': "Today's Plan",
    'todaysPlanDescription': 'View your scheduled visits for today - doctors and pharmacies.',
    'viewTodaysPlan': "View Today's Plan",
    'connectTitle': 'Connect with Healthcare Professionals',
    'connectDescription': 'Access a network of experienced doctors and build strong professional relationships.',
    'trackTitle': 'Track Your Performance',
    'trackDescription': 'Monitor your calls, visits, and sales performance with comprehensive analytics.',
    'manageTitle': 'Manage Samples & Orders',
    'manageDescription': 'Efficiently track samples distribution and manage client orders.',
    'hello': 'Hello',
    'welcome': 'Welcome',
    'recentReports': 'Recent Reports',
    'viewAll': 'View All',
    'quickAccess': 'Work Shortcuts',
    'dashboardStatistics': 'Dashboard Statistics',
    'doctorVisits': 'Doctor Visits',
    'samplesDistributed': 'Samples Distributed',
    'rcpaEntries': 'RCPA Entries',
    'tourDays': 'Tour Days',
    'offlineRequests': 'Offline Requests',
    'noOfflineRequests': 'No Offline Requests',
    'noOfflineRequestsDescription': 'There are no offline requests at the moment. All requests have been synchronized.',
    // RCPA
    'enterRCPA': 'Enter RCPA',
    'rcpa': 'RCPA',
    'rcpaEntry': 'RCPA Entry',
    'zenappBrand': 'Zenapp Brand (Virbac Brand)',
    'zenappValue': 'Zenapp Value (Virbac Value)',
    'competitorBrand': 'Competitor Brand',
    'competitorValue': 'Competitor Value (₹ INR)',
    'selectPharmacy': 'Select a Pharmacy',
    'selectBrand': 'Select Brand',
    'addZenappBrand': 'Add Zenapp Brand',
    'addVirbacBrand': 'Add Virbac Brand',
    'addCompetitor': 'Add Competitor',
    'actions': 'Actions',
    'signature': 'Signature',
    'clearSignature': 'Clear Signature',
    'signatureCaptured': 'Signature captured',
    'saveRCPA': 'Save RCPA',
    'rcpaSaved': 'RCPA saved successfully!',
    'lastRCPA': 'Last RCPA:',
    'rcpaPotentials': 'Rcpa-Potentials Vs Own',
    'rcpaTrendReport': 'RCPA Trend Report',
    'quickActions': 'Quick Actions',
}

const translations: Record<Language, Record<string, string>> = {
  en: englishTranslations,
  es: {
    'home': 'Inicio',
    'clients': 'Clientes',
    'customer360': 'Customer 360',
    'tourPlans': 'Planificación de Visitas',
    'eDetailing': 'E-Detalle',
    'leaves': 'Permisos',
    'samples': 'Muestras',
    'profile': 'Perfil',
    'reports': 'Analíticas e Informes',
    'sync': 'Sincronizar',
    'todaysPlan': 'Plan de Hoy',
    'dcr': 'DCR',
    'doctor360': 'Doctor Details',
    'expenseClaim': 'Reclamación de Gastos',
    'createExpenseClaim': 'Crear Reclamación',
    'orderBooking': 'Reserva de Pedidos',
    'rcpa': 'RCPA',
    'logout': 'Cerrar Sesión',
    'login': 'Iniciar Sesión',
    'email': 'Correo',
    'password': 'Contraseña',
    'rememberMe': 'Recordarme',
    'forgotPassword': '¿Olvidaste tu contraseña?',
    'back': 'Atrás',
    'submit': 'Enviar',
    'cancel': 'Cancelar',
    'save': 'Guardar',
    'edit': 'Editar',
    'delete': 'Eliminar',
    'view': 'Ver',
    'search': 'Buscar',
    'filter': 'Filtrar',
    'all': 'Todos',
    'doctors': 'Doctores',
    'pharmacy': 'Farmacia',
    'distributors': 'Distribuidores',
    'hospitals': 'Hospitales',
    'clinics': 'Clínicas',
    'viewDetails': 'Ver Detalles',
    'noClientsFound': 'No se encontraron clientes para esta categoría.',
    'todaysPlanTitle': 'Plan de Hoy',
    'todaysPlanDescription': 'Ver tus visitas programadas para hoy - doctores y farmacias.',
    'viewTodaysPlan': 'Ver Plan de Hoy',
    'connectTitle': 'Conectar con Profesionales de la Salud',
    'connectDescription': 'Accede a una red de doctores experimentados y construye relaciones profesionales sólidas.',
    'trackTitle': 'Rastrea Tu Rendimiento',
    'trackDescription': 'Monitorea tus llamadas, visitas y rendimiento de ventas con análisis completos.',
    'manageTitle': 'Gestionar Muestras y Pedidos',
    'manageDescription': 'Rastrea eficientemente la distribución de muestras y gestiona pedidos de clientes.',
    'hello': 'Hola',
    'welcome': 'Bienvenido',
    'recentReports': 'Informes Recientes',
    'viewAll': 'Ver Todo',
    'quickAccess': 'Acceso Rápido',
    'dashboardStatistics': 'Estadísticas del Panel',
    'doctorVisits': 'Visitas al Doctor',
    'samplesDistributed': 'Muestras Distribuidas',
    'rcpaEntries': 'Entradas RCPA',
    'tourDays': 'Días de Gira',
    'offlineRequests': 'Solicitudes Sin Conexión',
    'noOfflineRequests': 'No Hay Solicitudes Sin Conexión',
    'noOfflineRequestsDescription': 'No hay solicitudes sin conexión en este momento. Todas las solicitudes han sido sincronizadas.',
  },
  fr: {
    'home': 'Accueil',
    'clients': 'Clients',
    'customer360': 'Customer 360',
    'tourPlans': 'Planification des Visites',
    'eDetailing': 'E-Détail',
    'leaves': 'Congés',
    'samples': 'Échantillons',
    'profile': 'Profil',
    'reports': 'Analytique et Rapports',
    'sync': 'Synchroniser',
    'todaysPlan': "Plan d'Aujourd'hui",
    'dcr': 'DCR',
    'doctor360': 'Doctor Details',
    'expenseClaim': 'Réclamation de Frais',
    'createExpenseClaim': 'Créer une Réclamation',
    'orderBooking': 'Réservation de Commande',
    'rcpa': 'RCPA',
    'logout': 'Déconnexion',
    'login': 'Connexion',
    'email': 'Email',
    'password': 'Mot de passe',
    'rememberMe': 'Se souvenir de moi',
    'forgotPassword': 'Mot de passe oublié?',
    'back': 'Retour',
    'submit': 'Soumettre',
    'cancel': 'Annuler',
    'save': 'Enregistrer',
    'edit': 'Modifier',
    'delete': 'Supprimer',
    'view': 'Voir',
    'search': 'Rechercher',
    'filter': 'Filtrer',
    'all': 'Tous',
    'doctors': 'Médecins',
    'pharmacy': 'Pharmacie',
    'distributors': 'Distributeurs',
    'hospitals': 'Hôpitaux',
    'clinics': 'Cliniques',
    'viewDetails': 'Voir les Détails',
    'noClientsFound': 'Aucun client trouvé pour cette catégorie.',
    'todaysPlanTitle': "Plan d'Aujourd'hui",
    'todaysPlanDescription': 'Voir vos visites programmées pour aujourd\'hui - médecins et pharmacies.',
    'viewTodaysPlan': "Voir le Plan d'Aujourd'hui",
    'connectTitle': 'Se Connecter avec des Professionnels de la Santé',
    'connectDescription': 'Accédez à un réseau de médecins expérimentés et construisez des relations professionnelles solides.',
    'trackTitle': 'Suivez Votre Performance',
    'trackDescription': 'Surveillez vos appels, visites et performances de vente avec des analyses complètes.',
    'manageTitle': 'Gérer les Échantillons et Commandes',
    'manageDescription': 'Suivez efficacement la distribution d\'échantillons et gérez les commandes clients.',
    'hello': 'Bonjour',
    'welcome': 'Bienvenue',
    'recentReports': 'Rapports Récents',
    'viewAll': 'Voir Tout',
    'quickAccess': 'Accès Rapide',
    'dashboardStatistics': 'Statistiques du Tableau de Bord',
    'doctorVisits': 'Visites chez le Médecin',
    'samplesDistributed': 'Échantillons Distribués',
    'rcpaEntries': 'Entrées RCPA',
    'tourDays': 'Jours de Tournée',
    'offlineRequests': 'Demandes Hors Ligne',
    'noOfflineRequests': 'Aucune Demande Hors Ligne',
    'noOfflineRequestsDescription': 'Il n\'y a pas de demandes hors ligne pour le moment. Toutes les demandes ont été synchronisées.',
  },
  hi: {
    'home': 'होम',
    'clients': 'ग्राहक',
    'customer360': 'ग्राहक 360',
    'tourPlans': 'यात्रा नियोजन',
    'eDetailing': 'ई-विवरण',
    'leaves': 'छुट्टियां',
    'samples': 'इन्वेंटरी प्रबंधन',
    'profile': 'प्रोफ़ाइल',
    'reports': 'विश्लेषण और रिपोर्ट',
    'sync': 'सिंक करें',
    'todaysPlan': 'आज की योजना',
    'dcr': 'डीसीआर',
    'doctor360': 'डॉक्टर विवरण',
    'expenseClaim': 'व्यय दावा',
    'createExpenseClaim': 'व्यय दावा बनाएं',
    'orderBooking': 'ऑर्डर बुकिंग',
    'rcpa': 'आरसीपीए',
    'logout': 'लॉगआउट',
    'login': 'लॉगिन',
    'email': 'ईमेल',
    'password': 'पासवर्ड',
    'rememberMe': 'मुझे याद रखें',
    'forgotPassword': 'पासवर्ड भूल गए?',
    'back': 'वापस',
    'submit': 'जमा करें',
    'cancel': 'रद्द करें',
    'save': 'सहेजें',
    'edit': 'संपादित करें',
    'delete': 'हटाएं',
    'view': 'देखें',
    'search': 'खोजें',
    'filter': 'फ़िल्टर',
    'all': 'सभी',
    'doctors': 'डॉक्टर',
    'pharmacy': 'फार्मेसी',
    'distributors': 'वितरक',
    'hospitals': 'अस्पताल',
    'clinics': 'क्लीनिक',
    'viewDetails': 'विवरण देखें',
    'noClientsFound': 'इस श्रेणी के लिए कोई ग्राहक नहीं मिला।',
    'todaysPlanTitle': 'आज की योजना',
    'todaysPlanDescription': 'आज के लिए आपकी निर्धारित यात्राएं देखें - डॉक्टर और फार्मेसी।',
    'viewTodaysPlan': 'आज की योजना देखें',
    'connectTitle': 'हेल्थकेयर पेशेवरों के साथ जुड़ें',
    'connectDescription': 'अनुभवी डॉक्टरों के नेटवर्क तक पहुंचें और मजबूत पेशेवर संबंध बनाएं।',
    'trackTitle': 'अपने प्रदर्शन को ट्रैक करें',
    'trackDescription': 'व्यापक विश्लेषण के साथ अपने कॉल, यात्राओं और बिक्री प्रदर्शन की निगरानी करें।',
    'manageTitle': 'नमूने और ऑर्डर प्रबंधित करें',
    'manageDescription': 'नमूना वितरण को कुशलतापूर्वक ट्रैक करें और ग्राहक ऑर्डर प्रबंधित करें।',
    'hello': 'नमस्ते',
    'welcome': 'स्वागत है',
    'recentReports': 'हाल की रिपोर्ट',
    'viewAll': 'सभी देखें',
    'quickAccess': 'त्वरित पहुंच',
    'dashboardStatistics': 'डैशबोर्ड आंकड़े',
    'doctorVisits': 'डॉक्टर यात्राएं',
    'samplesDistributed': 'वितरित नमूने',
    'rcpaEntries': 'RCPA प्रविष्टियां',
    'tourDays': 'यात्रा दिवस',
    'offlineRequests': 'ऑफ़लाइन अनुरोध',
    'noOfflineRequests': 'कोई ऑफ़लाइन अनुरोध नहीं',
    'noOfflineRequestsDescription': 'इस समय कोई ऑफ़लाइन अनुरोध नहीं हैं। सभी अनुरोध सिंक्रनाइज़ किए गए हैं।',
  },
  th: {
    'home': 'หน้าแรก',
    'clients': 'ลูกค้า',
    'customer360': 'Customer 360',
    'tourPlans': 'การวางแผนการเยี่ยมชม',
    'eDetailing': 'E-Detailing',
    'leaves': 'การลา',
    'samples': 'ตัวอย่าง',
    'profile': 'โปรไฟล์',
    'reports': 'การวิเคราะห์และรายงาน',
    'sync': 'ซิงค์',
    'todaysPlan': 'แผนวันนี้',
    'dcr': 'DCR',
    'doctor360': 'Doctor Details',
    'expenseClaim': 'การเรียกร้องค่าใช้จ่าย',
    'createExpenseClaim': 'สร้างการเรียกร้อง',
    'orderBooking': 'การจองคำสั่งซื้อ',
    'rcpa': 'RCPA',
    'logout': 'ออกจากระบบ',
    'login': 'เข้าสู่ระบบ',
    'email': 'อีเมล',
    'password': 'รหัสผ่าน',
    'rememberMe': 'จำฉันไว้',
    'forgotPassword': 'ลืมรหัสผ่าน?',
    'back': 'กลับ',
    'submit': 'ส่ง',
    'cancel': 'ยกเลิก',
    'save': 'บันทึก',
    'edit': 'แก้ไข',
    'delete': 'ลบ',
    'view': 'ดู',
    'search': 'ค้นหา',
    'filter': 'กรอง',
    'all': 'ทั้งหมด',
    'doctors': 'แพทย์',
    'pharmacy': 'ร้านขายยา',
    'distributors': 'ผู้จัดจำหน่าย',
    'hospitals': 'โรงพยาบาล',
    'clinics': 'คลินิก',
    'viewDetails': 'ดูรายละเอียด',
    'noClientsFound': 'ไม่พบลูกค้าสำหรับหมวดหมู่นี้',
    'todaysPlanTitle': 'แผนวันนี้',
    'todaysPlanDescription': 'ดูการเยี่ยมชมที่กำหนดไว้สำหรับวันนี้ - แพทย์และร้านขายยา',
    'viewTodaysPlan': 'ดูแผนวันนี้',
    'connectTitle': 'เชื่อมต่อกับผู้เชี่ยวชาญด้านการดูแลสุขภาพ',
    'connectDescription': 'เข้าถึงเครือข่ายแพทย์ที่มีประสบการณ์และสร้างความสัมพันธ์ทางวิชาชีพที่แข็งแกร่ง',
    'trackTitle': 'ติดตามประสิทธิภาพของคุณ',
    'trackDescription': 'ตรวจสอบการโทร การเยี่ยมชม และประสิทธิภาพการขายของคุณด้วยการวิเคราะห์ที่ครอบคลุม',
    'manageTitle': 'จัดการตัวอย่างและคำสั่งซื้อ',
    'manageDescription': 'ติดตามการกระจายตัวอย่างอย่างมีประสิทธิภาพและจัดการคำสั่งซื้อของลูกค้า',
    'hello': 'สวัสดี',
    'welcome': 'ยินดีต้อนรับ',
    'recentReports': 'รายงานล่าสุด',
    'viewAll': 'ดูทั้งหมด',
    'quickAccess': 'การเข้าถึงด่วน',
    'dashboardStatistics': 'สถิติแดชบอร์ด',
    'doctorVisits': 'การเยี่ยมแพทย์',
    'samplesDistributed': 'ตัวอย่างที่แจกจ่าย',
    'rcpaEntries': 'รายการ RCPA',
    'tourDays': 'วันทัวร์',
    'offlineRequests': 'คำขอออฟไลน์',
    'noOfflineRequests': 'ไม่มีคำขอออฟไลน์',
    'noOfflineRequestsDescription': 'ไม่มีคำขอออฟไลน์ในขณะนี้ คำขอทั้งหมดได้รับการซิงค์แล้ว',
  },
  id: {
    'home': 'Beranda',
    'clients': 'Pelanggan',
    'customer360': 'Customer 360',
    'tourPlans': 'Perencanaan Kunjungan',
    'eDetailing': 'E-Detailing',
    'leaves': 'Cuti',
    'samples': 'Sampel',
    'profile': 'Profil',
    'reports': 'Analitik dan Laporan',
    'sync': 'Sinkronkan',
    'todaysPlan': 'Rencana Hari Ini',
    'dcr': 'DCR',
    'doctor360': 'Doctor Details',
    'expenseClaim': 'Klaim Pengeluaran',
    'createExpenseClaim': 'Buat Klaim',
    'orderBooking': 'Pemesanan Pesanan',
    'rcpa': 'RCPA',
    'logout': 'Keluar',
    'login': 'Masuk',
    'email': 'Email',
    'password': 'Kata Sandi',
    'rememberMe': 'Ingat saya',
    'forgotPassword': 'Lupa kata sandi?',
    'back': 'Kembali',
    'submit': 'Kirim',
    'cancel': 'Batal',
    'save': 'Simpan',
    'edit': 'Edit',
    'delete': 'Hapus',
    'view': 'Lihat',
    'search': 'Cari',
    'filter': 'Filter',
    'all': 'Semua',
    'doctors': 'Dokter',
    'pharmacy': 'Apotek',
    'distributors': 'Distributor',
    'hospitals': 'Rumah Sakit',
    'clinics': 'Klinik',
    'viewDetails': 'Lihat Detail',
    'noClientsFound': 'Tidak ada pelanggan ditemukan untuk kategori ini.',
    'todaysPlanTitle': 'Rencana Hari Ini',
    'todaysPlanDescription': 'Lihat kunjungan terjadwal Anda untuk hari ini - dokter dan apotek.',
    'viewTodaysPlan': 'Lihat Rencana Hari Ini',
    'connectTitle': 'Terhubung dengan Profesional Kesehatan',
    'connectDescription': 'Akses jaringan dokter berpengalaman dan bangun hubungan profesional yang kuat.',
    'trackTitle': 'Lacak Kinerja Anda',
    'trackDescription': 'Pantau panggilan, kunjungan, dan kinerja penjualan Anda dengan analitik komprehensif.',
    'manageTitle': 'Kelola Sampel & Pesanan',
    'manageDescription': 'Lacak distribusi sampel secara efisien dan kelola pesanan pelanggan.',
    'hello': 'Halo',
    'welcome': 'Selamat Datang',
    'recentReports': 'Laporan Terbaru',
    'viewAll': 'Lihat Semua',
    'quickAccess': 'Akses Cepat',
    'dashboardStatistics': 'Statistik Dashboard',
    'doctorVisits': 'Kunjungan Dokter',
    'samplesDistributed': 'Sampel yang Didistribusikan',
    'rcpaEntries': 'Entri RCPA',
    'tourDays': 'Hari Tur',
    'offlineRequests': 'Permintaan Offline',
    'noOfflineRequests': 'Tidak Ada Permintaan Offline',
    'noOfflineRequestsDescription': 'Tidak ada permintaan offline saat ini. Semua permintaan telah disinkronkan.',
  },
  my: {
    'home': 'Laman Utama',
    'clients': 'Pelanggan',
    'customer360': 'Customer 360',
    'tourPlans': 'Perancangan Lawatan',
    'eDetailing': 'E-Detailing',
    'leaves': 'Cuti',
    'samples': 'Sampel',
    'profile': 'Profil',
    'reports': 'Analitik dan Laporan',
    'sync': 'Segerakkan',
    'todaysPlan': 'Pelan Hari Ini',
    'dcr': 'DCR',
    'doctor360': 'Doctor Details',
    'expenseClaim': 'Tuntutan Perbelanjaan',
    'createExpenseClaim': 'Buat Tuntutan',
    'orderBooking': 'Tempahan Pesanan',
    'rcpa': 'RCPA',
    'logout': 'Log Keluar',
    'login': 'Log Masuk',
    'email': 'E-mel',
    'password': 'Kata Laluan',
    'rememberMe': 'Ingat saya',
    'forgotPassword': 'Lupa kata laluan?',
    'back': 'Kembali',
    'submit': 'Hantar',
    'cancel': 'Batal',
    'save': 'Simpan',
    'edit': 'Edit',
    'delete': 'Padam',
    'view': 'Lihat',
    'search': 'Cari',
    'filter': 'Tapis',
    'all': 'Semua',
    'doctors': 'Doktor',
    'pharmacy': 'Farmasi',
    'distributors': 'Pengedar',
    'hospitals': 'Hospital',
    'clinics': 'Klinik',
    'viewDetails': 'Lihat Butiran',
    'noClientsFound': 'Tiada pelanggan ditemui untuk kategori ini.',
    'todaysPlanTitle': 'Pelan Hari Ini',
    'todaysPlanDescription': 'Lihat lawatan yang dijadualkan untuk hari ini - doktor dan farmasi.',
    'viewTodaysPlan': 'Lihat Pelan Hari Ini',
    'connectTitle': 'Berhubung dengan Profesional Penjagaan Kesihatan',
    'connectDescription': 'Akses rangkaian doktor berpengalaman dan bina hubungan profesional yang kukuh.',
    'trackTitle': 'Jejak Prestasi Anda',
    'trackDescription': 'Pantau panggilan, lawatan, dan prestasi jualan anda dengan analitik komprehensif.',
    'manageTitle': 'Urus Sampel & Pesanan',
    'manageDescription': 'Jejak pengedaran sampel dengan cekap dan urus pesanan pelanggan.',
    'hello': 'Hello',
    'welcome': 'Selamat Datang',
    'recentReports': 'Laporan Terkini',
    'viewAll': 'Lihat Semua',
    'quickAccess': 'Akses Pantas',
    'dashboardStatistics': 'Statistik Papan Pemuka',
    'doctorVisits': 'Lawatan Doktor',
    'samplesDistributed': 'Sampel yang Diedarkan',
    'rcpaEntries': 'Entri RCPA',
    'tourDays': 'Hari Lawatan',
    'offlineRequests': 'Permintaan Luar Talian',
    'noOfflineRequests': 'Tiada Permintaan Luar Talian',
    'noOfflineRequestsDescription': 'Tiada permintaan luar talian pada masa ini. Semua permintaan telah disegerakkan.',
  },
  ne: {
    'home': 'गृह',
    'clients': 'ग्राहकहरू',
    'customer360': 'Customer 360',
    'tourPlans': 'भ्रमण योजना',
    'eDetailing': 'ई-विवरण',
    'leaves': 'छुट्टीहरू',
    'samples': 'नमुनाहरू',
    'profile': 'प्रोफाइल',
    'reports': 'विश्लेषण र रिपोर्टहरू',
    'sync': 'सिंक गर्नुहोस्',
    'todaysPlan': 'आजको योजना',
    'dcr': 'डीसीआर',
    'doctor360': 'डाक्टर विवरण',
    'expenseClaim': 'खर्च दावी',
    'createExpenseClaim': 'दावी बनाउनुहोस्',
    'orderBooking': 'अर्डर बुकिङ',
    'rcpa': 'RCPA',
    'logout': 'लगआउट',
    'login': 'लगइन',
    'email': 'इमेल',
    'password': 'पासवर्ड',
    'rememberMe': 'मलाई सम्झनुहोस्',
    'forgotPassword': 'पासवर्ड बिर्सनुभयो?',
    'back': 'फिर्ता',
    'submit': 'पेश गर्नुहोस्',
    'cancel': 'रद्द गर्नुहोस्',
    'save': 'बचत गर्नुहोस्',
    'edit': 'सम्पादन गर्नुहोस्',
    'delete': 'मेटाउनुहोस्',
    'view': 'हेर्नुहोस्',
    'search': 'खोज्नुहोस्',
    'filter': 'फिल्टर',
    'all': 'सबै',
    'doctors': 'डाक्टरहरू',
    'pharmacy': 'फार्मेसी',
    'distributors': 'वितरकहरू',
    'hospitals': 'अस्पतालहरू',
    'clinics': 'क्लिनिकहरू',
    'viewDetails': 'विवरण हेर्नुहोस्',
    'noClientsFound': 'यस श्रेणीको लागि कुनै ग्राहक फेला परेन।',
    'todaysPlanTitle': 'आजको योजना',
    'todaysPlanDescription': 'आजका लागि तपाईंको निर्धारित भ्रमणहरू हेर्नुहोस् - डाक्टरहरू र फार्मेसीहरू।',
    'viewTodaysPlan': 'आजको योजना हेर्नुहोस्',
    'connectTitle': 'स्वास्थ्य सेवा पेशेवरहरूसँग जोडिनुहोस्',
    'connectDescription': 'अनुभवी डाक्टरहरूको नेटवर्कमा पहुँच प्राप्त गर्नुहोस् र मजबूत व्यावसायिक सम्बन्धहरू निर्माण गर्नुहोस्।',
    'trackTitle': 'तपाईंको प्रदर्शन ट्र्याक गर्नुहोस्',
    'trackDescription': 'व्यापक विश्लेषणको साथ तपाईंका कलहरू, भ्रमणहरू र बिक्री प्रदर्शनको निगरानी गर्नुहोस्।',
    'manageTitle': 'नमूनाहरू र अर्डरहरू व्यवस्थापन गर्नुहोस्',
    'manageDescription': 'नमूनाहरूको वितरणलाई कुशलतापूर्वक ट्र्याक गर्नुहोस् र ग्राहक अर्डरहरू व्यवस्थापन गर्नुहोस्।',
    'hello': 'नमस्ते',
    'welcome': 'स्वागत छ',
    'recentReports': 'हालैका रिपोर्टहरू',
    'viewAll': 'सबै हेर्नुहोस्',
    'quickAccess': 'छिटो पहुँच',
    'dashboardStatistics': 'ड्यासबोर्ड तथ्याङ्क',
    'doctorVisits': 'डाक्टर भ्रमणहरू',
    'samplesDistributed': 'वितरित नमुनाहरू',
    'rcpaEntries': 'RCPA प्रविष्टिहरू',
    'tourDays': 'यात्रा दिनहरू',
    'offlineRequests': 'अफलाइन अनुरोधहरू',
    'noOfflineRequests': 'कुनै अफलाइन अनुरोध छैन',
    'noOfflineRequestsDescription': 'यस समय कुनै अफलाइन अनुरोध छैन। सबै अनुरोधहरू सिंक्रनाइज गरिएको छ।',
  },
  km: {
    'home': 'ទំព័រដើម',
    'clients': 'អតិថិជន',
    'customer360': 'Customer 360',
    'tourPlans': 'ការរៀបចំការទស្សនកិច្ច',
    'eDetailing': 'E-Detailing',
    'leaves': 'ការចាកចេញ',
    'samples': 'គំរូ',
    'profile': 'ប្រូហ្វាល',
    'reports': 'ការវិភាគ និងរបាយការណ៍',
    'sync': 'ធ្វើសមកាលកម្ម',
    'todaysPlan': 'ផែនការថ្ងៃនេះ',
    'dcr': 'DCR',
    'doctor360': 'Doctor Details',
    'expenseClaim': 'ការទាមទារចំណាយ',
    'createExpenseClaim': 'បង្កើតការទាមទារ',
    'orderBooking': 'ការកក់ការបញ្ជាទិញ',
    'rcpa': 'RCPA',
    'logout': 'ចេញ',
    'login': 'ចូល',
    'email': 'អ៊ីមែល',
    'password': 'ពាក្យសម្ងាត់',
    'rememberMe': 'ចងចាំខ្ញុំ',
    'forgotPassword': 'ភ្លេចពាក្យសម្ងាត់?',
    'back': 'ត្រឡប់',
    'submit': 'ដាក់ស្នើ',
    'cancel': 'បោះបង់',
    'save': 'រក្សាទុក',
    'edit': 'កែប្រែ',
    'delete': 'លុប',
    'view': 'មើល',
    'search': 'ស្វែងរក',
    'filter': 'តម្រង',
    'all': 'ទាំងអស់',
    'doctors': 'វេជ្ជបណ្ឌិត',
    'pharmacy': 'ឱសថស្ថាន',
    'distributors': 'អ្នកចែកចាយ',
    'hospitals': 'មន្ទីរពេទ្យ',
    'clinics': 'គ្លីនិក',
    'viewDetails': 'មើលព័ត៌មានលម្អិត',
    'noClientsFound': 'រកមិនឃើញអតិថិជនសម្រាប់ប្រភេទនេះទេ។',
    'todaysPlanTitle': 'ផែនការថ្ងៃនេះ',
    'todaysPlanDescription': 'មើលការទស្សនកិច្ចដែលបានកំណត់ពេលវេលាសម្រាប់ថ្ងៃនេះ - វេជ្ជបណ្ឌិត និងឱសថស្ថាន។',
    'viewTodaysPlan': 'មើលផែនការថ្ងៃនេះ',
    'connectTitle': 'តភ្ជាប់ជាមួយអ្នកជំនាញថែទាំសុខាភិបាល',
    'connectDescription': 'ចូលប្រើប្រាស់បណ្តាញវេជ្ជបណ្ឌិតដែលមានបទពិសោធន៍ និងកសាងទំនាក់ទំនងវិជ្ជាជីវៈដ៏រឹងមាំ។',
    'trackTitle': 'តាមដានការអនុវត្តរបស់អ្នក',
    'trackDescription': 'តាមដានការហៅទូរស័ព្ទ ការទស្សនកិច្ច និងការអនុវត្តលក់របស់អ្នកជាមួយនឹងការវិភាគទិន្នន័យដ៏ទូលំទូលាយ។',
    'manageTitle': 'គ្រប់គ្រងគំរូ និងការបញ្ជាទិញ',
    'manageDescription': 'តាមដានការចែកចាយគំរូដោយមានប្រសិទ្ធិភាព និងគ្រប់គ្រងការបញ្ជាទិញរបស់អតិថិជន។',
    'hello': 'សួស្តី',
    'welcome': 'សូមស្វាគមន៍',
    'recentReports': 'របាយការណ៍ថ្មីៗ',
    'viewAll': 'មើលទាំងអស់',
    'quickAccess': 'ការចូលប្រើប្រាស់រហ័ស',
    'dashboardStatistics': 'ស្ថិតិផ្ទាំងគ្រប់គ្រង',
    'doctorVisits': 'ការទស្សនកិច្ចវេជ្ជបណ្ឌិត',
    'samplesDistributed': 'គំរូដែលបានចែកចាយ',
    'rcpaEntries': 'ធាតុ RCPA',
    'tourDays': 'ថ្ងៃដំណើរ',
    'offlineRequests': 'សំណើ Offline',
    'noOfflineRequests': 'មិនមានសំណើ Offline',
    'noOfflineRequestsDescription': 'មិនមានសំណើ offline នៅពេលនេះទេ។ សំណើទាំងអស់ត្រូវបានធ្វើសមកាលកម្មរួចហើយ។',
  },
  'my-MM': {
    'home': 'ပင်မစာမျက်နှာ',
    'clients': 'ဖောက်သည်များ',
    'customer360': 'Customer 360',
    'tourPlans': 'လည်ပတ်မှု စီမံကိန်း',
    'eDetailing': 'E-Detailing',
    'leaves': 'ခွင့်ယူမှုများ',
    'samples': 'နမူနာများ',
    'profile': 'ကိုယ်ရေးအချက်အလက်',
    'reports': 'ခွဲခြမ်းစိတ်ဖြာမှု နှင့် အစီရင်ခံစာများ',
    'sync': 'ထပ်တူပြုရန်',
    'todaysPlan': 'ယနေ့အစီအစဉ်',
    'dcr': 'DCR',
    'doctor360': 'Doctor Details',
    'expenseClaim': 'အသုံးစရိတ်တောင်းဆိုမှု',
    'createExpenseClaim': 'တောင်းဆိုမှုဖန်တီးရန်',
    'orderBooking': 'အမှာစာမှာယူမှု',
    'rcpa': 'RCPA',
    'logout': 'ထွက်ရန်',
    'login': 'ဝင်ရောက်ရန်',
    'email': 'အီးမေးလ်',
    'password': 'စကားဝှက်',
    'rememberMe': 'မှတ်ထားပါ',
    'forgotPassword': 'စကားဝှက်မေ့နေပါသလား?',
    'back': 'ပြန်သွားရန်',
    'submit': 'တင်သွင်းရန်',
    'cancel': 'ပယ်ဖျက်ရန်',
    'save': 'သိမ်းဆည်းရန်',
    'edit': 'တည်းဖြတ်ရန်',
    'delete': 'ဖျက်ရန်',
    'view': 'ကြည့်ရန်',
    'search': 'ရှာဖွေရန်',
    'filter': 'စစ်ထုတ်ရန်',
    'all': 'အားလုံး',
    'doctors': 'ဆရာဝန်များ',
    'pharmacy': 'ဆေးဆိုင်',
    'distributors': 'ဖြန့်ဖြူးသူများ',
    'hospitals': 'ဆေးရုံများ',
    'clinics': 'ဆေးခန်းများ',
    'viewDetails': 'အသေးစိတ်ကြည့်ရန်',
    'noClientsFound': 'ဤအမျိုးအစားအတွက် ဖောက်သည်များ မတွေ့ရှိပါ။',
    'todaysPlanTitle': 'ယနေ့အစီအစဉ်',
    'todaysPlanDescription': 'ယနေ့အတွက် သင်စီစဉ်ထားသော လည်ပတ်မှုများကို ကြည့်ရန် - ဆရာဝန်များနှင့် ဆေးဆိုင်များ။',
    'viewTodaysPlan': 'ယနေ့အစီအစဉ်ကို ကြည့်ရန်',
    'connectTitle': 'ကျန်းမာရေးစောင့်ရှောက်မှု ပညာရှင်များနှင့် ချိတ်ဆက်ရန်',
    'connectDescription': 'အတွေ့အကြုံရှိသော ဆရာဝန်များ၏ ကွန်ရက်သို့ ဝင်ရောက်ပြီး ခိုင်မာသော လုပ်ငန်းဆက်ဆံရေး ဆက်ဆံမှုများ တည်ဆောက်ရန်။',
    'trackTitle': 'သင်၏စွမ်းဆောင်ရည်ကို ခြေရာခံရန်',
    'trackDescription': 'သင့်ခေါ်ဆိုမှုများ၊ လည်ပတ်မှုများနှင့် ရောင်းအားစွမ်းဆောင်ရည်ကို ကျယ်ပြန့်သော ခွဲခြမ်းစိတ်ဖြာမှုဖြင့် စောင့်ကြည့်ရန်။',
    'manageTitle': 'နမူနာများနှင့် အမှာစာများကို စီမံရန်',
    'manageDescription': 'နမူနာဖြန့်ဖြူးမှုကို ထိရောက်စွာ ခြေရာခံပြီး ဖောက်သည်အမှာစာများကို စီမံရန်။',
    'hello': 'မင်္ဂလာပါ',
    'welcome': 'ကြိုဆိုပါသည်',
    'recentReports': 'လတ်တလော အစီရင်ခံစာများ',
    'viewAll': 'အားလုံးကြည့်ရန်',
    'quickAccess': 'အမြန်ဝင်ရောက်ခွင့်',
    'dashboardStatistics': 'ဒက်ရှ်ဘုတ် စာရင်းဇယား',
    'doctorVisits': 'ဆရာဝန် လည်ပတ်မှုများ',
    'samplesDistributed': 'ဖြန့်ဝေထားသော နမူနာများ',
    'rcpaEntries': 'RCPA ထည့်သွင်းမှုများ',
    'tourDays': 'ခရီးစဉ် ရက်များ',
    'offlineRequests': 'အော့ဖ်လိုင်း တောင်းဆိုမှုများ',
    'noOfflineRequests': 'အော့ဖ်လိုင်း တောင်းဆိုမှု မရှိပါ',
    'noOfflineRequestsDescription': 'လက်ရှိအချိန်တွင် အော့ဖ်လိုင်း တောင်းဆိုမှု မရှိပါ။ တောင်းဆိုမှုအားလုံး ထပ်တူပြုပြီးဖြစ်သည်။',
  },
  si: {
    'home': 'මුල් පිටුව',
    'clients': 'ගනුදෙනුකරුවන්',
    'customer360': 'Customer 360',
    'tourPlans': 'සංචාර සැලසුම්',
    'eDetailing': 'E-Detailing',
    'leaves': 'විවේක',
    'samples': 'නියමු',
    'profile': 'පැතිකඩ',
    'reports': 'විශ්ලේෂණ සහ වාර්තා',
    'sync': 'සමමුහුර්ත කරන්න',
    'todaysPlan': 'අද සැලැස්ම',
    'dcr': 'DCR',
    'doctor360': 'Doctor Details',
    'expenseClaim': 'අයවැය හිමිකම',
    'createExpenseClaim': 'හිමිකමක් සාදන්න',
    'orderBooking': 'ඇණවුම් කිරීම',
    'rcpa': 'RCPA',
    'logout': 'පිටවීම',
    'login': 'පිවිසීම',
    'email': 'විද්‍යුත් තැපෑල',
    'password': 'මුරපදය',
    'rememberMe': 'මාව මතක තබා ගන්න',
    'forgotPassword': 'මුරපදය අමතකද?',
    'back': 'ආපසු',
    'submit': 'ඉදිරිපත් කරන්න',
    'cancel': 'අවලංගු කරන්න',
    'save': 'සුරකින්න',
    'edit': 'සංස්කරණය කරන්න',
    'delete': 'මකන්න',
    'view': 'බලන්න',
    'search': 'සොයන්න',
    'filter': 'පෙරහන',
    'all': 'සියල්ල',
    'doctors': 'වෛද්‍යවරු',
    'pharmacy': 'ඖෂධ ශාලාව',
    'distributors': 'බෙදාහරින්නන්',
    'hospitals': 'රෝහල්',
    'clinics': 'වෛද්‍යාගාර',
    'viewDetails': 'විස්තර බලන්න',
    'noClientsFound': 'මෙම කාණ්ඩය සඳහා ගනුදෙනුකරුවන් හමු නොවීය.',
    'todaysPlanTitle': 'අද සැලැස්ම',
    'todaysPlanDescription': 'අද සඳහා ඔබගේ නියමිත සංචාර බලන්න - වෛද්‍යවරු සහ ඖෂධ ශාලා.',
    'viewTodaysPlan': 'අද සැලැස්ම බලන්න',
    'connectTitle': 'සෞඛ්‍ය සේවා වෘත්තිකයන් සමඟ සම්බන්ධ වන්න',
    'connectDescription': 'අත්දැකීම් සහිත වෛද්‍යවරුන්ගේ ජාලයට ප්‍රවේශ වී සෞඛ්‍ය වෘත්තීය සම්බන්ධතා ගොඩනඟන්න.',
    'trackTitle': 'ඔබගේ කාර්ය සාධනය ලුහුබැඳීම',
    'trackDescription': 'විස්තෘත විශ්ලේෂණ සමඟ ඔබගේ ඇමතුම්, සංචාර සහ විකුණුම් කාර්ය සාධනය නිරීක්ෂණය කරන්න.',
    'manageTitle': 'නියමු සහ ඇණවුම් කළමනාකරණය',
    'manageDescription': 'නියමු බෙදා හැරීම කාර්යක්ෂමව ලුහුබැඳීම සහ ගනුදෙනුකරු ඇණවුම් කළමනාකරණය.',
    'hello': 'හෙලෝ',
    'welcome': 'ආයුබෝවන්',
    'recentReports': 'මෑත වාර්තා',
    'viewAll': 'සියල්ල බලන්න',
    'quickAccess': 'වේගවත් ප්‍රවේශය',
    'dashboardStatistics': 'උපකරණ පුවරු සංඛ්‍යාලේඛන',
    'doctorVisits': 'වෛද්‍ය සංචාර',
    'samplesDistributed': 'බෙදා හරින ලද නියමු',
    'rcpaEntries': 'RCPA ඇතුළත් කිරීම්',
    'tourDays': 'සංචාර දින',
    'offlineRequests': 'ඔෆ්ලයින් ඉල්ලීම්',
    'noOfflineRequests': 'ඔෆ්ලයින් ඉල්ලීම් නැත',
    'noOfflineRequestsDescription': 'මේ මොහොතේ ඔෆ්ලයින් ඉල්ලීම් නැත. ඉල්ලීම් සියල්ල සමමුහුර්ත කර ඇත.',
  },
  ta: {
    'home': 'முகப்பு',
    'clients': 'வாடிக்கையாளர்கள்',
    'customer360': 'வாடிக்கையாளர் 360',
    'tourPlans': 'வருகை திட்டமிடல்',
    'eDetailing': 'இ-விவரம்',
    'leaves': 'விடுப்புகள்',
    'samples': 'மாதிரிகள்',
    'profile': 'சுயவிவரம்',
    'reports': 'பகுப்பாய்வு மற்றும் அறிக்கைகள்',
    'sync': 'ஒத்திசை',
    'todaysPlan': 'இன்றைய திட்டம்',
    'dcr': 'DCR',
    'doctor360': 'Doctor Details',
    'expenseClaim': 'செலவு கோரிக்கை',
    'createExpenseClaim': 'கோரிக்கை உருவாக்க',
    'orderBooking': 'ஆர்டர் பதிவு',
    'rcpa': 'RCPA',
    'logout': 'வெளியேறு',
    'login': 'உள்நுழை',
    'email': 'மின்னஞ்சல்',
    'password': 'கடவுச்சொல்',
    'rememberMe': 'என்னை நினைவில் கொள்ளுங்கள்',
    'forgotPassword': 'கடவுச்சொல் மறந்துவிட்டதா?',
    'back': 'பின்',
    'submit': 'சமர்ப்பி',
    'cancel': 'ரத்துசெய்',
    'save': 'சேமி',
    'edit': 'திருத்து',
    'delete': 'நீக்கு',
    'view': 'காண்க',
    'search': 'தேடு',
    'filter': 'வடிகட்டு',
    'all': 'அனைத்தும்',
    'doctors': 'மருத்துவர்கள்',
    'pharmacy': 'மருந்தகம்',
    'distributors': 'விநியோகஸ்தர்கள்',
    'hospitals': 'மருத்துவமனைகள்',
    'clinics': 'மருத்துவமனைகள்',
    'viewDetails': 'விவரங்களைக் காண்க',
    'noClientsFound': 'இந்த வகைக்கு வாடிக்கையாளர்கள் எதுவும் கிடைக்கவில்லை.',
    'todaysPlanTitle': 'இன்றைய திட்டம்',
    'todaysPlanDescription': 'இன்றைய திட்டமிடப்பட்ட வருகைகளைக் காண்க - மருத்துவர்கள் மற்றும் மருந்தகங்கள்.',
    'viewTodaysPlan': 'இன்றைய திட்டத்தைக் காண்க',
    'connectTitle': 'சுகாதார நிபுணர்களுடன் இணைக்க',
    'connectDescription': 'அனுபவமிக்க மருத்துவர்களின் நெட்வொர்க்கை அணுகி வலுவான தொழில்முறை உறவுகளை உருவாக்குங்கள்.',
    'trackTitle': 'உங்கள் செயல்திறனைக் கண்காணிக்க',
    'trackDescription': 'விரிவான பகுப்பாய்வுடன் உங்கள் அழைப்புகள், வருகைகள் மற்றும் விற்பனை செயல்திறனைக் கண்காணிக்க.',
    'manageTitle': 'மாதிரிகள் மற்றும் ஆர்டர்களை நிர்வகிக்க',
    'manageDescription': 'மாதிரி விநியோகத்தை திறமையாகக் கண்காணித்து வாடிக்கையாளர் ஆர்டர்களை நிர்வகிக்க.',
    'hello': 'வணக்கம்',
    'welcome': 'வரவேற்கிறோம்',
    'recentReports': 'சமீபத்திய அறிக்கைகள்',
    'viewAll': 'அனைத்தையும் காண்க',
    'quickAccess': 'விரைவான அணுகல்',
    'dashboardStatistics': 'டாஷ்போர்டு புள்ளிவிவரங்கள்',
    'doctorVisits': 'மருத்துவர் வருகைகள்',
    'samplesDistributed': 'விநியோகிக்கப்பட்ட மாதிரிகள்',
    'rcpaEntries': 'RCPA உள்ளீடுகள்',
    'tourDays': 'சுற்றுப்பயண நாட்கள்',
    'offlineRequests': 'ஆஃப்லைன் கோரிக்கைகள்',
    'noOfflineRequests': 'ஆஃப்லைன் கோரிக்கைகள் இல்லை',
    'noOfflineRequestsDescription': 'இப்போது ஆஃப்லைன் கோரிக்கைகள் இல்லை. அனைத்து கோரிக்கைகளும் ஒத்திசைக்கப்பட்டுள்ளன.',
  },
  fil: {
    'home': 'Home',
    'clients': 'Mga Customer',
    'customer360': 'Customer 360',
    'tourPlans': 'Pagpaplano ng Pagbisita',
    'eDetailing': 'E-Detailing',
    'leaves': 'Mga Leave',
    'samples': 'Mga Sample',
    'profile': 'Profile',
    'reports': 'Analytics at Mga Report',
    'sync': 'I-sync',
    'todaysPlan': 'Plano Ngayon',
    'dcr': 'DCR',
    'doctor360': 'Doctor Details',
    'expenseClaim': 'Expense Claim',
    'createExpenseClaim': 'Gumawa ng Claim',
    'orderBooking': 'Order Booking',
    'rcpa': 'rcpa',
    'logout': 'Logout',
    'login': 'Login',
    'email': 'Email',
    'password': 'Password',
    'rememberMe': 'Tandaan ako',
    'forgotPassword': 'Nakalimutan ang password?',
    'back': 'Bumalik',
    'submit': 'Ipasa',
    'cancel': 'Kanselahin',
    'save': 'I-save',
    'edit': 'I-edit',
    'delete': 'Tanggalin',
    'view': 'Tingnan',
    'search': 'Maghanap',
    'filter': 'Filter',
    'all': 'Lahat',
    'doctors': 'Mga Doktor',
    'pharmacy': 'Pharmacy',
    'distributors': 'Mga Distributor',
    'hospitals': 'Mga Hospital',
    'clinics': 'Mga Clinic',
    'viewDetails': 'Tingnan ang Detalye',
    'noClientsFound': 'Walang nahanap na customer para sa kategoryang ito.',
    'todaysPlanTitle': 'Plano Ngayon',
    'todaysPlanDescription': 'Tingnan ang iyong naka-iskedyul na pagbisita para sa ngayon - mga doktor at pharmacy.',
    'viewTodaysPlan': 'Tingnan ang Plano Ngayon',
    'connectTitle': 'Kumonekta sa mga Healthcare Professional',
    'connectDescription': 'I-access ang network ng may karanasang mga doktor at bumuo ng malakas na propesyonal na relasyon.',
    'trackTitle': 'Subaybayan ang Iyong Performance',
    'trackDescription': 'Subaybayan ang iyong mga tawag, pagbisita, at sales performance na may komprehensibong analytics.',
    'manageTitle': 'Pamahalaan ang mga Sample at Order',
    'manageDescription': 'Subaybayan nang mahusay ang pamamahagi ng sample at pamahalaan ang mga order ng client.',
    'hello': 'Hello',
    'welcome': 'Maligayang Pagdating',
    'recentReports': 'Kamakailang Mga Report',
    'viewAll': 'Tingnan Lahat',
    'quickAccess': 'Mabilis na Access',
    'dashboardStatistics': 'Dashboard Statistics',
    'doctorVisits': 'Mga Pagbisita sa Doktor',
    'samplesDistributed': 'Mga Sample na Naipamahagi',
    'rcpaEntries': 'Mga Entry ng RCPA',
    'tourDays': 'Mga Araw ng Tour',
    'offlineRequests': 'Mga Offline Request',
    'noOfflineRequests': 'Walang Offline Request',
    'noOfflineRequestsDescription': 'Walang offline request sa ngayon. Lahat ng request ay na-synchronize na.',
  },
  // New Indian languages - using English as placeholder (fallback already handled)
  te: { ...englishTranslations }, // Telugu - to be expanded
  kn: { ...englishTranslations }, // Kannada - to be expanded
  ml: { ...englishTranslations }, // Malayalam - to be expanded
  gu: { ...englishTranslations }, // Gujarati - to be expanded
  mr: { ...englishTranslations }, // Marathi - to be expanded
  bn: { ...englishTranslations }, // Bengali - to be expanded
  pa: { ...englishTranslations }, // Punjabi - to be expanded
  ur: { ...englishTranslations }, // Urdu - to be expanded
}

const getTranslations = (lang: Language): Record<string, string> => {
  return translations[lang] || translations.en
}